application: lyfeon-init
version: 1
runtime: php
api_version: 1

handlers:
- url: /images
  static_dir: images
  
- url: /assets
  static_dir: assets

- url: /apis
  static_dir: apis

- url: /co/.*
  static_files: co/co.html
  upload: co/co.html
  
#- url: /co/services/company.php
#  script: /co/services/company.php

- url: /about.php
  script: about.php

- url: /stream.php
  script: stream.php
  
- url: /.*
  script: welcome_page.php
  
#- url: /
#  static_files: assets/index.html
#  upload: assets/index.html

