application: lyfeon-init
version: 1
runtime: php
api_version: 1

handlers:
- url: /images
  static_dir: images
  
- url: /assets
  static_dir: assets
  
- url: /about.php
  script: about.php
  
- url: /.*
  script: welcome_page.php
  
#- url: /
#  static_files: assets/index.html
#  upload: assets/index.html

