application: lyfeon-init
version: 1
runtime: php
api_version: 1
threadsafe: true
  
handlers:
- url: /images
  static_dir: images
  
- url: /assets
  static_dir: assets
  
- url: /includes/generalactions/.*
  script: includes/generalactions.php
  
#  Apis url
#- url: /apis/(/?.*?)
- url: /api/write/.*  
  script: api/write.php

- url: /api/search/.*
  script: api/search.php

- url: /api/delete/.*
  script: api/delete.php

- url: /api/modify/.*
  script: api/modify.php

- url: /api/analytics/.*
  script: api/analytics.php
  
- url: /queue/.*
  script: queue.php

- url: /worker/tagextractor/.*
  script: worker/tagextractor.php

- url: /worker/tagremover/.*
  script: worker/tagremover.php
  
- url: /worker/tagmodifier/.*
  script: worker/tagmodifier.php
  
  # Co url
- url: /co/analytics/analytics
  script: co/analytics/analytics.php

- url: /co/investors/investors
  script: co/investors/investors.php
  
- url: /co/people/people
  script: co/people/people.php

- url: /co/services/company
  script: co/services/company.php
  
- url: /co/services/contact
  script: co/services/contact.php
  
- url: /co/services/help
  script: co/services/help.php
  
- url: /co/services/terms
  script: co/services/terms.php
  
- url: /co(/?.*?)
  script: co/co.php
  
- url: /about
  script: about.php

- url: /stream
  script: stream.php

- url: /u/.*
  script: u.php

- url: /note/.*
  script: note.php

- url: /user_account(/?.*?)
  script: user_account.php

- url: /manage_expenses
  script: manage_expenses.php

- url: /manage_reminders
  script: manage_reminders.php

#- url: /+
- url: /.*
  script: welcome_page.php

#error_handlers:
 # - file: error.php
  
 #- error_code: over_quota
  #  file: over_quota.html

#- url: /.*
#  script: error_404.php


